version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node

    steps:
      - checkout
      - run:
          name: Installing Dependancies
          command: npm i
      - run:
          name: Building The App
          command: npm run build

      - save_cache:
          key: node-modules
          paths:
            - /src/node_modules

  test:
    docker:
      - image: cimg/node

    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules

      - run:
          name: Installing Dependencies
          command: npm i

      - run:
          name: Running Tests
          command: npm tun test

  analyze:
    docker:
      - image: cimg/node

    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules

      - run:
          name: Installing Dependencies
          command: npm i

      - run:
          name: Anlyzing Code
          command: npm audit


workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
